services:
  sogo:
    image: sonroyaalmerol/docker-sogo:5.12.7
    container_name: sogo
    restart: unless-stopped
    networks:
      caddy:
      mariadb:
      mailserver:
      memcached:
    depends_on:
      caddy:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      keycloak-configure:
        condition: service_completed_successfully
      mariadb:
        condition: service_healthy
      mailserver:
        condition: service_healthy
      memcached:
        condition: service_healthy
    environment:
      TZ: UTC
      DOMAIN: ${DOMAIN}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      PUID: ${DOCKER_USER_ID:-1000}
      PGID: ${DOCKER_GROUP_ID:-1000}
      MARIADB_ADMIN_PASSWORD: ${MARIADB_ADMIN_PASSWORD}
      SOGO_DB_HOST: mariadb
      SOGO_DB_PORT: 3306
      SOGO_DB_NAME: sogo
      SOGO_DB_USER: sogo
      SOGO_DB_PASSWORD: ${SOGO_DB_PASSWORD}
      SOGO_MEMCACHED_HOST: memcached
      SOGO_OAUTH_SECRET: ${SOGO_OAUTH_SECRET}
    entrypoint:
      - /bin/bash
      - /entrypoint-wrapper.sh
    volumes:
      - sogo_spool:/var/spool/sogo
      - caddy_ca:/ca:ro
      - ./configs/sogo/entrypoint.sh:/entrypoint-wrapper.sh:ro
      - ./configs/sogo/sogo.conf:/config-templates/sogo.conf.template:ro
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS http://127.0.0.1/SOGo/ >/dev/null
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s

volumes:
  sogo_spool:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${STACK_VOLUME_ROOT}/sogo_spool
